# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 916b666f85b556f54c45e8178b7c0f8b4bef62b205bd6cf760c694152a757f3518c22a53fe7a2786ae9fd0c84478ce6e45da7bebc48b3dea8e1cacd856ff5b98
  PUBLISHABLE_KEY: pk_test_6pRNASCoBOKtIshFeQd4XMUh
  SECRET_KEY: sk_test_BQokikJOvBiI2HlWgH4olfQ2

test:
  secret_key_base: 7b5f45cddf9c2b42f6bbc5ea9a7006dd27f230c6a2ea3760d5839084c6e735c5e58c5c813a440d23bf9b9c053c241911a7d989004b05fec7bbf3c17ec1059332

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
